### This notebook deals with the instability arising out using the frs BC for traces and tries to find out if there is a mismatch between the input T and S and that at our boundaries at the time when the model is initialised (IC state is equal to the BC at time t = 0)

In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import netCDF4 as nc
import xarray as xr
import matplotlib.cm as cm
from scipy.interpolate import interp1d
from salishsea_tools import (nc_tools, gsw_calls, viz_tools)

#### Let us load the IC for our NEMO model

In [27]:
IC_file = nc.Dataset('/ocean/ssahu/CANYONS/wcvi/initial_conditions/West_coast_NEMO_IC_temperature_salinity_nomask_JP.nc')

In [28]:
votem_IC = IC_file.variables['votemper'][:];
vosal_IC = IC_file.variables['vosaline'][:];

In [29]:
votem_IC.shape

(1, 27, 100, 70)

#### Now let us load the T and S for the BC file (Let's begin the excersize by loading only the BC file of the west boundary)

In [30]:
BC_west = nc.Dataset('/ocean/ssahu/CANYONS/bdy_files/3d_NEMO_west_m04.nc');

In [31]:
votem_west_BC = BC_west.variables['votemper'][:];
vosal_west_BC = BC_west.variables['vosaline'][:];

In [32]:
votem_west_BC.shape

(43, 27, 4, 100)

#### By principle the outer values at the very first time step should be equal to the value of the IC (let's test that)

In [33]:
BC_check = votem_west_BC[0,:,:,:]; print(BC_check.shape)

IC_check = votem_IC[0,:,:]; print (IC_check.shape)

(27, 4, 100)
(27, 100, 70)


In [34]:
np.mean(BC_check)

4.5696635

In [35]:
np.mean(IC_check[:,:,:4])

4.5006418

#### So they are not same and our fears just became real

In [11]:
BC_check[0,...]

array([[ 11.26034641,  11.24334621,  11.24070263,  11.23822403,
         11.22112751,  11.19831944,  11.20296288,  11.22289371,
         11.23872852,  11.26172924,  11.25253773,  11.18979836,
         11.12477112,  11.08434582,  11.03537273,  10.94834614,
         10.83931923,  10.76751041,  10.740798  ,  10.72731972,
         10.71774483,  10.70897865,  10.67700577,  10.63631916,
         10.61370277,  10.6175375 ,  10.62753773,  10.63834572,
         10.64879799,  10.65515423,  10.66360664,  10.67098999,
         10.66692066,  10.63546848,  10.56756401,  10.48611164,
         10.44856358,  10.44137287,  10.42972851,  10.41382504,
         10.40446854,  10.40392017,  10.41346836,  10.42592049,
         10.43372917,  10.43553734,  10.43325043,  10.42305851,
         10.41341496,  10.40431976,  10.40231895,  10.41522408,
         10.43938828,  10.46419716,  10.48419666,  10.5051012 ,
         10.52190971,  10.52310181,  10.50003242,  10.46222401,
         10.40486717,  10.32905865,  10.

In [25]:
np.where(IC_check[0,...] == np.max(IC_check[0,...]))

(array([0]), array([65]))

In [18]:
BC_check[0,0,0]

11.260346

In [24]:
np.where(IC_check[0,...] == BC_check[0,...])

/home/ssahu/anaconda3/lib/python3.5/site-packages/ipykernel/__main__.py:1: DeprecationWarning: elementwise == comparison failed; this will raise an error in the future.
  if __name__ == '__main__':


(array([], dtype=int64),)

In [23]:
np.where(BC_check[0,...] == np.max(BC_check[0,...]))

(array([3]), array([5]))

In [28]:
IC_check[0,0,60]

11.024442

In [29]:
BC_check[0,3,5]

11.303032

In [22]:
np.where(BC_check == IC_check)

/home/ssahu/anaconda3/lib/python3.5/site-packages/ipykernel/__main__.py:1: DeprecationWarning: elementwise == comparison failed; this will raise an error in the future.
  if __name__ == '__main__':


(array([], dtype=int64),)